config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users

  get 'welcome/index'

  get 'welcome/about'

  resources :users, only: [:index, :show] do
    resources :items, only: [:create, :destroy] do
      put :toggle
    end
  end

  root 'users#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :items, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, id: :devise_controller?
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password) }
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create

    @user = User.find(params[:user_id])

    @item = @user.items.new

    @item.name = params[:item][:name]

    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to @user
    else
      flash[:error] = "Thee was an error saving the item. Please try again."
      redirect_to @user
    end
  end

  def destroy
    @user = User.find(params[:user_id])
#    @item = Item.find(params[:id])
    @item = @user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "\"#{@item.name}\" was completed successfully!"
    else
      flash[:error] = "There was an error completing the task."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def toggle
    #load item
    #mark as complete/incomplete, save
    #redirect

    @user = User.find(params[:user_id])
    @item = @user.items.find(params[:item_id])

    @item.completed = !@item.completed

    if @item.save
      flash[:notice] = "\"#{@item.name}\" was updated!"
    else
      flash[:error] = "There was an error updating the task."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    @items = @user.items

    @item = Item.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h4> Add an item </h4>
<%= form_for [user, item] do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'sr-only' %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter a new item" %>
  </div>
  <%= f. submit "Add Item", class: 'btn btn-default pull-right' %>
<% end %>

app/views/items/_item.html.erb
<%= content_tag :div, class: 'media', id: "item-#{item.id}" do %>
  <div class="media">
    <div class="media-body">
      <h4><%= link_to "", user_item_toggle_path(item.user, item), method: :put, remote: true, class: "glyphicon glyphicon-#{item.completed ? 'ok' : 'unchecked'}"  %><%= item.name %>
        <small>
            expires in <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %>
        </small>
      </h4>
    </div>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).hide();
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
<% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/items/toggle.js.erb
<% if @item.valid? %>
  $('#item-' +<%= @item.id %>).html("<%= escape_javascript(render(@item)) %>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
<% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class-"close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class-"alert alert-warning">
          <button type="button" class="close" sata-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
  </div>
  <div class="container">
    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.username %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> - <%= link_to "All Users", users_path, :class => 'navbar-link' %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
 </div>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class = "container">
  <h1>All Users</h1>
  <% @users.each do |user| %>
    <p><%= link_to user.username, user_path(user.id) %></p>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class = "container">
  <h2>User: <%= @user.username %></h2>

  <div>
    <h3>To do:</h3>
    <%= render @items %>
  </div>
  <% if current_user %>
    <%= render 'items/form', item: Item.new, user: @user %>
  <% end %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>